import React from 'react';
const Footer = () => {
    return (React.createElement("footer", { className: "bg-[#005F73] text-white py-8" },
        React.createElement("div", { className: "container mx-auto px-6" },
            React.createElement("div", { className: "flex flex-col md:flex-row justify-between mb-6" },
                React.createElement("div", { className: "mb-4 md:mb-0" },
                    React.createElement("h4", { className: "text-lg font-bold" }, "About Us"),
                    React.createElement("p", { className: "mt-2 text-sm" }, "We are dedicated to providing the best hotel booking experience for our users.")),
                React.createElement("div", { className: "mb-4 md:mb-0" },
                    React.createElement("h4", { className: "text-lg font-bold" }, "Quick Links"),
                    React.createElement("ul", { className: "mt-2" },
                        React.createElement("li", null,
                            React.createElement("a", { href: "#", className: "hover:text-[#90E0EF] transition" }, "Home")),
                        React.createElement("li", null,
                            React.createElement("a", { href: "#", className: "hover:text-[#90E0EF] transition" }, "About")),
                        React.createElement("li", null,
                            React.createElement("a", { href: "#", className: "hover:text-[#90E0EF] transition" }, "Services")),
                        React.createElement("li", null,
                            React.createElement("a", { href: "#", className: "hover:text-[#90E0EF] transition" }, "Contact")))),
                React.createElement("div", { className: "mb-4 md:mb-0" },
                    React.createElement("h4", { className: "text-lg font-bold" }, "Contact Us"),
                    React.createElement("p", { className: "mt-2 text-sm" }, "Email: support@hotelbooking.com"),
                    React.createElement("p", { className: "text-sm" }, "Phone: (123) 456-7890")),
                React.createElement("div", null,
                    React.createElement("h4", { className: "text-lg font-bold" }, "Follow Us"),
                    React.createElement("div", { className: "flex space-x-4 mt-2" },
                        React.createElement("a", { href: "#", className: "text-[#90E0EF] hover:text-white transition" },
                            React.createElement("i", { className: "fab fa-facebook-f" })),
                        React.createElement("a", { href: "#", className: "text-[#90E0EF] hover:text-white transition" },
                            React.createElement("i", { className: "fab fa-twitter" })),
                        React.createElement("a", { href: "#", className: "text-[#90E0EF] hover:text-white transition" },
                            React.createElement("i", { className: "fab fa-instagram" }))))),
            React.createElement("div", { className: "border-t border-gray-700 pt-4 text-center text-sm" }, "\u00A9 2024 HotelBooking.com. All rights reserved."))));
};
export default Footer;
